services:

  db:
    image: mongodb/mongodb-community-server:latest
    container_name: isare_db
    ports: 
      - 27017:27017
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass

  api:
    image: jave_tinder_isare
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    ports:
      - 3001:3000
    volumes:
      - ./src:/app/src